### ISSUE TITLE
Add to the django-rest-framework grid on Django Packages.

### ISSUE THREAD

**Issue by lovelydinosaur** [s2krish/django-restify#1]
Adding to this grid would be good for the project visibility... https://www.djangopackages.com/grids/g/django-rest-framework/

**Comment by s2krish** [comment]
@tomchristie yea exactly, I was thinking. How do I do this?

**Comment by lovelydinosaur** [comment]
Log in with github then I think there's a link on homepage to add a new package.

**Comment by s2krish** [comment]
thanks @tomchristie, added! Not sure why I couldn't see the Add Package to Grid link (I am 100 % sure it was not there for DRF grid)
